### ISSUE TITLE
Unable to log into your Ely.by account

### ISSUE THREAD

**Issue by ghost** [rePublic-Studios/BetterGDLauncher#1]
TypeError: Cannot read property '0' of undefined

This error appears when I click 'Sign In'

**Comment by Nyakaze** [comment]
This bug is not fixed yet.
It happens when you have a Ely.By account without a skin.

Please select a skin on the ely.by page, after that you can login with it.

We are working on the fix!

**Comment by ghost** [comment]
Seems fixed
